Remove index
opengovsg/GoGovSG pull request #1054
Opened 2020-12-14 06:55 UTC by Oxiang

## Problem

Now that the production database uses **urls_combined_weighted_search_idx**, **urls_weighted_search_idx** is obsolete and can be deleted.

The previous db migration script that was meant to create **urls_combined_weighted_search_idx** is unused as sequelize handles the index creation. The script can be remove as well.

## Solution

- New db_migration script to delete urls_weighted_search_idx index
- Remove 20201202_add_combined_search_index migration script from codebase

2020-12-14 06:57 UTC, LoneRifle requested changes
we don't usually remove scripts for migrations. lgtm otherwise.

2020-12-14 07:01 UTC, Oxiang commented
> we don't usually remove scripts for migrations. lgtm otherwise.

In this case we did not use the migration script at all, would leaving it in cause confusion?

2020-12-14 07:05 UTC, LoneRifle commented
Ah, that's true. let me change it.

2020-12-14 07:05 UTC, LoneRifle approved these changes

2020-12-15 05:58 UTC, yong-jie approved these changes

2020-12-15 05:59 UTC, merged