refactor(QRCodeService): replaced jsdom and d3 libraries with cheerio
opengovsg/GoGovSG pull request #1286
Opened 2021-03-09 10:47 UTC by orbitalsqwib

## Problem

Currently, the jsdom and d3 libraries have been imported to generate HTML for the QRCodeService module.
However, we only use a small subset of the functionalities contained within these libraries.

## Solution

Replaced jsdom and d3 libraries with cheerio to reduce client app memory footprint.
Closes #1284.

**New dependencies**:

- `cheerio` : Lightweight markup parser that can traverse and manipulate HTML.

**New dev dependencies**:

- `@types/cheerio` : Supplies types for cheerio

2021-03-09 11:15 UTC, liangyuanruo commented
Do you have any metrics to back up this PR?

2021-03-09 12:03 UTC, orbitalsqwib commented
as of now i haven’t evaluated the metrics, but potentially they would be the application load speed and the qr code generation speed

2021-03-10 01:38 UTC, orbitalsqwib commented
Update: I realised I can't evaluate the application load speed as the files are stored locally on my device, however I checked the bundle sizes for cheerio, jsdom and d3 on Bundlephobia and found that cheerio's bundle footprint is about 323.8kB minified, while jsdom and d3 are 2.9MB and 278.8kB minified respectively.

After gzipping, cheerio is at 88.5kB while jsdom and d3 are 726kB and 86.7kB respectively. Hence, there should theoretically be a 89% reduction in the bundle footprint for this code segment specifically.

2021-03-10 01:46 UTC, liangyuanruo commented
> Hence, there should theoretically be an 89% reduction in the bundle footprint for this code segment specifically.

Actually, there is zero change in bundle size because the QR code service is on the server.

2021-03-10 02:10 UTC, LoneRifle commented
@liangyuanruo another reason to replace jsdom and d3 is that of dependency management - cheerio is lighter and has fewer dependencies than jsdom+d3 (7 vs 23 + 30), and despite having a limited API relative to d3, is still suitable enough for our usecase of generating SVGs. Given that we only use a tiny subset of the incumbents (ie, jsdom to create a DOM and d3.select to manipulate the DOM), it makes sense to have the libraries replaced, so that generally, we minimise the number of dependency updates that we may get but not need, particularly from d3.

2021-03-10 02:50 UTC, liangyuanruo commented
Still doesn't sound like a very strong reason to change battle-tested server-side code, but if you insist... I see that we have unit tests in `qrcode.test.ts` so I don't suppose this will break anything.

2021-03-10 02:52 UTC, LoneRifle commented
> btw can help to remove the unnecessary typecast in the unit tests in `qrcode.test.ts`?
> 
> ```ts
> const buffer = (await qrCodeService.createGoQrCode(
>         testUrl,
>         ImageFormat.PNG,
>       )) as Buffer
> ```

@orbitalsqwib can get to that once he's subjected the codebase to k6 testing

2021-03-10 03:38 UTC, liangyuanruo commented
sure thing, thanks!

2021-03-10 04:01 UTC, LoneRifle requested changes
See this and the other request to remove the test

2021-03-10 04:01 UTC, LoneRifle commented on src/server/modules/qr/services/QrCodeService.ts
> +    }
So how about..
```suggestion
    lines.forEach((line, i) => {
      const linkDOM = cheerio.load('')
      linkDOM('body').append('<text></text>')
      linkDOM('text')
        .attr('x', `${textLocationX}`)
        .attr('y', `${textLocationY + i * FONT_SIZE * LINE_HEIGHT}`)
        .attr('text-anchor', 'middle')
        .attr('font-family', 'sans-serif')
        .attr('font-weight', '400')
        .attr('font-size', `${FONT_SIZE}px`)
        .text(line)

      svg.append(`${linkDOM('body').html()}`)
    })
```

2021-03-10 04:03 UTC, LoneRifle commented
Note that this PR also upgrades package-lock to v2.

2021-03-11 07:50 UTC, merged