refactor(redirect): make into self-contained module
opengovsg/GoGovSG pull request #940
Opened 2020-11-23 05:15 UTC by LoneRifle

## Context

As part of a wider effort to reorganise the codebase around
domain-specific modules, consolidate all redirect-related
objects into a redirect module, under the `redirect/` dir.

TODO: Move tests to under src, move link statistics logging to
AnalyticsLoggerService

Ongoing work for #869 

## Solution

- create a new redirect dir, for the redirect module
- create a Redirect class in `redirect/index.ts`, holding the
  redirect endpoint and the endpoint for gtag.js, and accessible
  via `Redirect.router`. Make this injectable via inversify

- Rework `server/index.ts` to mount `Redirect.router` on top of
  `redirectSpecificMiddleware`, so that gtag.js endpoint now
  has the session cookie. This is deliberate to better organise
  the codebase

- Move routing, controller, services, types to `redirect/`
- GaLogger -> AnalyticsLogger
- Remove all interfaces for redirection

### Improvements

Under this new module-centric scheme, the `index.ts` of the module 
will export by default something that is mountable into express, either 
a router or a controller. The index file will also export relevant controllers
and types by name.

Also take the trouble to dispense with interfaces. By and large, we
no longer have to use interfaces to specify a contract in TypeScript
[1]. Moreover, because we don't actually have multiple implementations
of the interfaces we have declared, we can just use classes, and then
mock the class using the `Required<T>` utility type in TypeScript [2]

References:
[1]: https://docs.microsoft.com/en-gb/archive/blogs/kcwalina/api-design-myth-interface-as-contract
[2]: https://stackoverflow.com/questions/31876947/confused-about-the-interface-and-class-coding-guidelines-for-typescript

- Details ...

2020-11-23 05:25 UTC, LoneRifle commented
Failure is due to a decrease in code coverage owing to a reorg

2020-11-25 02:15 UTC, liangyuanruo commented on src/server/inversify.config.ts
> +  addRedirectBindings(container)
i'm still trying to understand the value of this abstraction, given that all the other bindings are performed inline above, and other developers can tell at a glance what's happening. is it supposed to be the start of introducing a loader pattern? but then, the implementation is specific to the redirect module.

it's only partially abstracting away DI, which is an edge case. can we leave it out as a separate PR until we're ready to tackle the entire thing?

2020-11-25 02:18 UTC, liangyuanruo requested changes
i'd like to prioritise ease of reading of the codebase. i think `addRedirectBindings` is introducing complexity rather than removing it. if you want to introduce the `makeRouter` pattern, do it at a later stage in a separate PR?

2020-11-25 02:46 UTC, LoneRifle commented
> i'd like to prioritise ease of reading of the codebase. i think `addRedirectBindings` is introducing complexity rather than removing it. if you want to introduce the `makeRouter` pattern, do it at a later stage in a separate PR?

Is this a change in your position? Previous discussions indicate you were alright with having the module handle its own inversify dep injection

2020-11-25 03:37 UTC, LoneRifle commented on test/server/modules/redirect/RedirectController.test.ts
> +    req.headers['user-agent'] = userAgent
Out of scope of the commit? I would have thought the priority would be reorganisation

2020-11-25 05:40 UTC, liangyuanruo approved these changes
> Is this a change in your position? Previous discussions indicate you were alright with having the module handle its own inversify dep injection

As discussed, let's look into performing this refactor in a separate issue.

2020-11-25 05:44 UTC, merged