Include long links into search
opengovsg/GoGovSG pull request #998
Opened 2020-12-02 03:31 UTC by Oxiang

## Problem

Currently, users are only able to search keywords based on short links and description. However, users are also searching long links as recorded by google analytics.

Partially address #977 

## Solution

**Improvements**:

- Add longUrl as part of search vector
- Script for db migration to include longUrl into the search index
- description ranking is dropped to the lowest as they are no longer being filled by users
- shortUrl ranking still remains at the top as they are the most frequently used keywords

2020-12-02 05:31 UTC, liangyuanruo submitted a review, later dismissed
actually, instead of dropping the existing index, could we have both the old and new indexes co-exist? this will allow the database to support both old and new application versions, which will be necessary if there is a rollback.

2020-12-02 08:27 UTC, LoneRifle requested changes

2020-12-02 08:27 UTC, LoneRifle commented on src/server/models/url.ts
> +        name: 'new_urls_weighted_search_idx',
please, never claim something is new. a more appropriate name could be `url_entry_weighted_search_idx` or similar

2020-12-08 05:36 UTC, LoneRifle approved these changes
lgtm

2020-12-08 05:49 UTC, merged